sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: gfVeypt3bHUFRoS73oLl7w1NA1mqkqZ6P8Q+A2ttsW/xwF3Z/lPa7kwx1u0z38riW7zdrJKqFphAEpPqfWm8zPYQ4gBx8r/cIv9m0Q0pYfKtXwT265OBdXuChPiT9/gyFVpd3Fzpo1mV15m13oA+4F08Vq/6yuv6Pb9ZegtXCDPSMIOYhphwsV8ygPG7cWhIM+lxAnZE7zfBRLEdKSKuugwVURUE0rf/6rzDY4IQT5ywa7sOD2MshYiB+XNCVBjdUteVCyww4+MgP7iQRgfN36XDt1k6g7CCzJ96SW0qWNXJav+4Zy/c3ovm80yanyTueDdXgFQKk9wXDzRfu38RgvIqycMMeY5BEJzwS2Z8gD0kwdDLgy3KbkHGNQZ4Iaa9GEdMlygXoqVmxCHngaYkKMyBB9hFbvqwMhwlkHFwi1zt9kriBOGsnGGWk+do79aqkoRNs2rF7eINu7g9u/ZfODsUL7yJaY5f2aEJtLsFTsxvyyt/XuM6/Qsl61SOHX+XUJd30RjSITYhS6eJ/WQXYju66zSKr6rb7/HrmSsolYPG2nCnp4sh9d2n563610Fs8GDTOX71nzw4XUpdVclXhIcHcksJeOAEfKKMFTGinZr7w8cAddnPiOHqPoeQfshZbbR/ioTXhMXkYQiEsgTDcx73+mzbgZtwLRxbEndE1ko=
